// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUeexG9-IgXGWUSgGTRO17p3Iv4pJPcdM',
    appId: '1:742142932041:web:b24fa84dadd3c368353b98',
    messagingSenderId: '742142932041',
    projectId: 'todo-dev-6dd87',
    authDomain: 'todo-dev-6dd87.firebaseapp.com',
    storageBucket: 'todo-dev-6dd87.appspot.com',
    measurementId: 'G-VHV5ZX0VZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC28ftknHljC9g5sQPLhSssA2u-rAlP8bE',
    appId: '1:742142932041:android:77d1a197eb71cf66353b98',
    messagingSenderId: '742142932041',
    projectId: 'todo-dev-6dd87',
    storageBucket: 'todo-dev-6dd87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA30K_7uSThYv-yiP7rAx9pkFtauXCXIE',
    appId: '1:742142932041:ios:1688a6411f3e11b4353b98',
    messagingSenderId: '742142932041',
    projectId: 'todo-dev-6dd87',
    storageBucket: 'todo-dev-6dd87.appspot.com',
    iosBundleId: 'com.example.todoCrud',
  );
}
